### ISSUE TITLE
Apple Homekit

### ISSUE THREAD

**Issue by Wachiwi** [harpoonhq/home-assistant-project#1]
As DS I want to have the possibility to control home-assistant with my Apple devices. To be more specific I want to be able to control home-assistant devices via the native HomeKit integration.

**Blockers**:

*None*

**Subtasks**:

*None*

**Acceptance criterias**:
- [X] Everything is documented [wiki](/harpoonhq/home-assistant-project/wiki/Homekit-support)
- [ ] Multiple devices where successfully tested by different stakeholders

**Comment by tfresh1** [comment]
you have to add the install instructions for the right npm version
`
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs
`

**Comment by Wachiwi** [comment]
Updated wiki entry
