### ISSUE TITLE
OSRAM

### ISSUE THREAD

**Issue by Wachiwi** [harpoonhq/home-assistant-project#4]
As a general user I want to have support for my Osram smart home light (bulbs).

**Requirements**:

- ZigBee Support

**Blockers**:

- [x] #12 

**Subtasks**:

*None*

**Acceptance criterias**:
- [x] Everything is documented inside the (wiki)
- [x] Multiple components where successfully tested by different stakeholders

**Comment by Wachiwi** [comment]
Would need some more documentation.

**Comment by Wachiwi** [comment]
@shoesch starting documentation inside the wiki at this weekend.

**Comment by shoesch** [comment]
Now I updated the wiki.

Look at [OSRAM-Lights](https://github.com/harpoonhq/home-assistant-project/wiki/OSRAM-Lights) if you want to know, how to add a bulb from OSRAM to deCONZ via the Webinterface.
